describe("#system", function()
  local system = require 'std.system'

  describe("platform", function()
    it("should not be nil", function()
      assert.not_nil(system.platform())
    end)
  end)
  describe("version", function()
    it("should not be nil", function()
      assert.not_nil(system.version())
    end)
  end)
  describe("cpu_count", function()
    it("should not be > 0", function()
      assert.is_true(system.cpu_count() > 0)
    end)
  end)
  describe("cpu_arch", function()
    it("should not be nil", function()
      assert.not_nil(system.cpu_arch())
    end)
  end)
  describe("cpu_endianness", function()
    it("should not be nil", function()
      assert.not_nil(system.cpu_endianness())
    end)
  end)
  describe("memory_total", function()
    it("should not be nil", function()
      assert.not_nil(system.memory_total())
    end)
    it("should be > 0", function()
      assert.is_true(system.memory_total() > 0)
    end)
  end)
  describe("memory_free", function()
    it("should not be nil", function()
      assert.not_nil(system.memory_free())
    end)
    it("should be > 0", function()
      assert.is_true(system.memory_free() > 0)
    end)
  end)
  describe("hostname", function()
    it("should not be nil", function()
      assert.not_nil(system.hostname())
    end)
  end)
  describe("user_name", function()
    it("should not be nil", function()
      assert.not_nil(system.user_name())
    end)
  end)
  describe("user_home", function()
    it("should not be nil", function()
      assert.not_nil(system.user_home())
    end)
  end)
end)
